CREATE TABLE IF NOT EXISTS "nations" (
    "id" integer,
    "alliance_id": integer,
    "alliance_position" tinyint,
    "alliance_position_id" integer,
    "nation_name" text,
    "leader_name" text,
    "continent" tinyint,
    "war_policy" tinyint,
    "domestic_policy" tinyint,
    "color" tinyint,
    "num_cities" integer,
    "score" numeric,
    "population" integer,
    "flag" text,
    "vacation_mode_turns" integer,
    "beige_turns" integer,
    "espionage_available" boolean,,
    "last_active" timestamp with time zone,
    "date" timestamp with time zone,
    "soldiers" integer,
    "tanks" integer,
    "aircraft" integer,
    "ships" integer,
    "missiles" integer,
    "nukes" integer,
    "spies" integer,
    "soldiers_today" integer,
    "tanks_today" integer,
    "aircraft_today" integer,
    "ships_today" integer,
    "missiles_today" integer,
    "nukes_today" integer,
    "spies_today" integer,
    "discord" text,
    "discord_id" text,
    "turns_since_last_city" integer,
    "turns_since_last_project" integer,
    "projects" integer,
    "project_bits" bigint,
    "moon_landing_date" timestamp with time zone,
    "mars_landing_date" timestamp with time zone,
    "wars_won" integer,
    "wars_lost" integer,
    "tax_id" integer,
    "alliance_seniority" integer,
    "gross_national_income" numeric,
    "gross_domestic_product" numeric,
    "soldier_casualties" integer,
    "soldier_kills" integer,
    "tank_casualties" integer,
    "tank_kills" integer,
    "aircraft_casualties" integer,
    "aircraft_kills" integer,
    "ship_casualties" integer,
    "ship_kills" integer,
    "missile_casualties" integer,
    "missile_kills" integer,
    "nuke_casualties" integer,
    "nuke_kills" integer,
    "spy_casualties" integer,
    "spy_kills" integer,
    "money_looted" numeric,
    "vip" boolean,,
    "commendations" integer,
    "denouncements" integer,
    "economic_policy" smallint,
    "social_policy" smallint,
    "government_type" smallint,
    "credits_redeemed_this_month" integer,
    "alliance_join_date" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "nations_private" (
    "id" integer,
    "spy_attacks" integer,
    "update_tz" numeric,
    "money" numeric,
    "coal" numeric,
    "oil" numeric,
    "uranium" numeric,
    "iron" numeric,
    "bauxite" numeric,
    "lead" numeric,
    "gasoline" numeric,
    "munitions" numeric,
    "steel" numeric,
    "aluminum" numeric,
    "food" numeric,
    "credits" integer
);

CREATE TABLE IF NOT EXISTS "alliances" (
    "id" integer,
    "name" text,
    "acronym" text,
    "score" numeric,
    "color" tinyint,
    "date" timestamp with time zone,
    "average_score" numeric,
    "accept_members" boolean,
    "flag" text,
    "forum_link" text,
    "discord_link" text,
    "wiki_link" text
);

CREATE TABLE IF NOT EXISTS "alliances_private" (
    "id" integer,
    "money" numeric,
    "coal" numeric,
    "oil" numeric,
    "uranium" numeric,
    "iron" numeric,
    "bauxite" numeric,
    "lead" numeric,
    "gasoline" numeric,
    "munitions" numeric,
    "steel" numeric,
    "aluminum" numeric,
    "food" numeric
);

CREATE TABLE IF NOT EXISTS "cities" (
    "id" integer,
    "nation_id" integer,
    "name" text,
    "date" timestamp with time zone,
    "infrastructure" numeric,
    "land" numeric,
    "powered" boolean,
    "oil_power" integer,
    "wind_power" integer,
    "coal_power" integer,
    "nuclear_power" integer,
    "coal_mine" integer,
    "oil_well" integer,
    "uranium_mine" integer,
    "barracks" integer,
    "farm" integer,
    "police_station" integer,
    "hospital" integer,
    "recycling_center" integer,
    "subway" integer,
    "supermarket" integer,
    "bank" integer,
    "shopping_mall" integer,
    "stadium" integer,
    "lead_mine" integer,
    "iron_mine" integer,
    "bauxite_mine" integer,
    "oil_refinery" integer,
    "aluminum_refinery" integer,
    "steel_mill" integer,
    "munitions_factory" integer,
    "factory" integer,
    "hangar" integer,
    "drydock" integer,
    "nuke_date" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "trades" (
    "id" integer,
    "type" tinyint,
    "date" timestamp with time zone,
    "sender_id" integer,
    "receiver_id" integer,
    "offer_resource" tinyint,
    "offer_amount" integer,
    "buy_or_sell" text,
    "price" integer,
    "accepted" boolean,
    "date_accepted" timestamp with time zone,
    "original_trade_id" integer
);

CREATE TABLE IF NOT EXISTS "bankrecs" (
    "id" integer,
    "date" timestamp with time zone,
    "sender_id" integer,
    "sender_type" tinyint,
    "receiver_id" integer,
    "receiver_type" tinyint,
    "banker_id" integer,
    "note" text,
    "money" numeric,
    "coal" numeric,
    "oil" numeric,
    "uranium" numeric,
    "iron" numeric,
    "bauxite" numeric,
    "lead" numeric,
    "gasoline" numeric,
    "munitions" numeric,
    "steel" numeric,
    "aluminum" numeric,
    "food" numeric
    "tax_id" integer
);

CREATE TABLE IF NOT EXISTS "treaties" (
    "id" integer,
    "date" timestamp with time zone,
    "treaty_type" tinyint,
    "treaty_url" text,
    "turns_left" integer,
    "sender_id" integer,
    "receiver_id" integer,
    "approved" boolean
);

CREATE TABLE IF NOT EXISTS "colors" (
    "color" smallint,
    "bloc_name" text,
    "turn_bonus" integer
);

CREATE TABLE IF NOT EXISTS "wars" (
    "id" integer,
    "date" timestamp with time zone,
    "reason" text,
    "war_type" tinyint,
    "att_id" integer,
    "att_alliance_id" integer,
    "def_id" integer,
    "def_alliance_id" integer,
    "ground_control" integer,
    "air_superiority" integer,
    "naval_blockade" integer,
    "winner_id" integer,
    "turns_left" integer,
    "att_points" integer,
    "def_points" integer,
    "att_peace" boolean,
    "def_peace" boolean,
    "att_resistance" integer,
    "def_resistance" integer,
    "att_fortify" boolean,
    "def_fortify" boolean,
    "att_gas_used" numeric,
    "def_gas_used" numeric,
    "att_mun_used" numeric,
    "def_mun_used" numeric,
    "att_alum_used" numeric,
    "def_alum_used" numeric,
    "att_steel_used" numeric,
    "def_steel_used" numeric,
    "att_infra_destroyed" numeric,
    "def_infra_destroyed" numeric,
    "att_money_looted" numeric,
    "def_money_looted" numeric,
    "def_soldiers_lost" integer,
    "att_soldiers_lost" integer,
    "def_tanks_lost" integer,
    "att_tanks_lost" integer,
    "def_aircraft_lost" integer,
    "att_aircraft_lost" integer,
    "def_ships_lost" integer,
    "att_ships_lost" integer,
    "att_missiles_used" integer,
    "def_missiles_used" integer,
    "att_nukes_used" integer,
    "def_nukes_used" integer,
    "att_infra_destroyed_value" numeric,
    "def_infra_destroyed_value" numeric
);

CREATE TABLE IF NOT EXISTS "war_attacks" (
    "id" integer,
    "date" timestamp with time zone,
    "att_id" integer,
    "def_id" integer,
    "type" tinyint,
    "war_id" integer,
    "victor" integer,
    "success" tinyint,
    "city_id" integer,
    "infra_destroyed" numeric,
    "improvements_lost" integer,
    "money_stolen" numeric,
    "resistance_lost" integer,
    "city_infra_before" numeric,
    "infra_destroyed_value" numeric,
    "att_mun_used" numeric,
    "def_mun_used" numeric,
    "att_gas_used" numeric,
    "def_gas_used" numeric,
    "money_destroyed" numeric,
    "military_salvage_aluminum" numeric,
    "military_salvage_steel" numeric,
    "att_soldiers_used" integer,
    "att_soldiers_lost" integer,
    "def_soldiers_used" integer,
    "def_soldiers_lost" integer,
    "att_tanks_used" integer,
    "att_tanks_lost" integer,
    "def_tanks_used" integer,
    "def_tanks_lost" integer,
    "att_aircraft_used" integer,
    "att_aircraft_lost" integer,
    "def_aircraft_used" integer,
    "def_aircraft_lost" integer,
    "att_ships_used" integer,
    "att_ships_lost" integer,
    "def_ships_used" integer,
    "def_ships_lost" integer,
    "att_missiles_lost" integer,
    "def_missiles_lost" integer,
    "att_nukes_lost" integer,
    "def_nukes_lost" integer,
    "improvements_destroyed" text,
    "infra_destroyed_percentage" numeric,
    "cities_infra_before" numeric,
    "money_looted" numeric,
    "coal_looted" numeric,
    "oil_looted" numeric,
    "uranium_looted" numeric,
    "iron_looted" numeric,
    "bauxite_looted" numeric,
    "lead_looted" numeric,
    "gasoline_looted" numeric,
    "munitions_looted" numeric,
    "steel_looted" numeric,
    "aluminum_looted" numeric,
    "food_looted" numeric
);

CREATE TABLE IF NOT EXISTS "treasures" (
    "name" text,
    "color" smallint,
    "continent" smallint,
    "bonus" integer,
    "spawn_date" timestamp with time zone,
    "nation_id" integer
);

CREATE TABLE IF NOT EXISTS "radiation" (
    "north_america" numeric,
    "south_america" numeric,
    "europe" numeric,
    "africa" numeric,
    "asia" numeric,
    "australia" numeric,
    "antarctica" numeric
);

CREATE TABLE IF NOT EXISTS "bounties" (
    "id" integer,
    "date" timestamp with time zone,
    "nation_id" integer,
    "amount" integer,
    "type" tinyint
);

CREATE TABLE IF NOT EXISTS "tax_brackets" (
    "id" integer,
    "alliance_id" integer,
    "date" timestamp with time zone,
    "date_modified" timestamp with time zone,
    "last_modifier_id" integer,
    "tax_rate" integer,
    "resource_tax_rate" integer,
    "bracket_name" text
);

CREATE TABLE IF NOT EXISTS "tradeprices" (
    "id" integer,
    "date" timestamp with time zone,
    "money" numeric,
    "coal" numeric,
    "oil" numeric,
    "uranium" numeric,
    "iron" numeric,
    "bauxite" numeric,
    "lead" numeric,
    "gasoline" numeric,
    "munitions" numeric,
    "steel" numeric,
    "aluminum" numeric,
    "food" numeric,
    "credits" integer
)

CREATE TABLE IF NOT EXISTS "treasure_trades" (
    "id" integer,
    "offer_date" timestamp with time zone,
    "accept_date" timestamp with time zone,
    "sender_id" integer,
    "receiver_id" integer,
    "buying" boolean,
    "selling" boolean,
    "treasure" text,
    "money" integer,
    "accepted" boolean,
    "rejected" boolean,
    "seller_cancelled" boolean
);

CREATE TABLE IF NOT EXISTS "embargoes" (
    "id" integer,
    "date" timestamp with time zone,
    "sender_id" integer,
    "receiver_id" integer,
    "reason" text,
    "type" tinyint
);

CREATE TABLE IF NOT EXISTS "banned_nations" (
    "nation_id" integer,
    "reason" text,
    "date" timestamp with time zone,
    "days_left" integer
)