"""
Autolycus REST API Application

This module creates and configures the Flask application for the
Autolycus REST API, providing endpoints for raids, builds, and damage
calculator features.

Security:
    All protected endpoints require token-based authentication via
    ephemeral links generated by the Discord bot. See api/security.py
    for implementation details.

Usage:
    from api.app import create_app
    app = create_app()
    app.run()
"""
import logging
import os
from typing import Optional

from dotenv import load_dotenv
from flask import Flask, jsonify
from flask_cors import CORS

# Load environment variables FIRST
load_dotenv()

from api.config import get_config
from api.routes.auth import auth_bp
from api.routes.builds import builds_bp
from api.routes.damage import damage_bp
from api.routes.raids import raids_bp

logger = logging.getLogger(__name__)


def create_app(config_object: Optional[object] = None) -> Flask:
    """
    Application factory for creating Flask app instances.
    
    Args:
        config_object: Optional configuration object. If not provided,
                      configuration is loaded based on FLASK_ENV.
    
    Returns:
        Configured Flask application instance.
    """
    app = Flask(__name__)
    
    # Load configuration
    if config_object:
        app.config.from_object(config_object)
    else:
        config = get_config()
        app.config.from_object(config)
    
    # Ensure required config values are set
    if not app.config.get('SECRET_KEY'):
        app.config['SECRET_KEY'] = os.urandom(32).hex()
        logger.warning("No SECRET_KEY configured, using random key. "
                      "Tokens will be invalidated on restart.")
    
    # Configure CORS
    cors_origins = app.config.get('CORS_ORIGINS', ['*'])
    CORS(app, origins=cors_origins, supports_credentials=True, 
         allow_headers=['Content-Type', 'Authorization'],
         methods=['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE'])
    
    # Register blueprints
    app.register_blueprint(auth_bp)
    app.register_blueprint(raids_bp)
    app.register_blueprint(builds_bp)
    app.register_blueprint(damage_bp)
    
    # Health check endpoint
    @app.route('/api/health')
    def health_check():
        """Health check endpoint for monitoring."""
        return jsonify({
            'status': 'healthy',
            'service': 'autolycus-api',
            'version': os.getenv('version', 'unknown'),
        }), 200
    
    # Root endpoint
    @app.route('/')
    def root():
        """Root endpoint."""
        return jsonify({
            'message': 'Autolycus API',
            'documentation': '/api/docs',
            'health': '/api/health',
        }), 200
    
    # Error handlers
    @app.errorhandler(404)
    def not_found(error):
        """Handle 404 errors."""
        return jsonify({
            'error': 'Not found',
            'message': 'The requested resource does not exist.',
            'code': 'NOT_FOUND'
        }), 404
    
    @app.errorhandler(500)
    def internal_error(error):
        """Handle 500 errors."""
        logger.error(f"Internal server error: {error}", exc_info=True)
        return jsonify({
            'error': 'Internal server error',
            'message': 'An unexpected error occurred.',
            'code': 'INTERNAL_ERROR'
        }), 500
    
    @app.errorhandler(405)
    def method_not_allowed(error):
        """Handle 405 errors."""
        return jsonify({
            'error': 'Method not allowed',
            'message': 'This HTTP method is not supported for this endpoint.',
            'code': 'METHOD_NOT_ALLOWED'
        }), 405
    
    logger.info(f"Autolycus API initialized with CORS origins: {cors_origins}")
    
    return app


def run_api():
    """
    Run the API server using Waitress (production WSGI server).
    
    This function is called when running the API standalone.
    """
    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(levelname)s %(asctime)s.%(msecs)d %(name)s: %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )
    
    try:
        from waitress import serve
        
        app = create_app()
        host = app.config.get('HOST', '0.0.0.0')
        port = app.config.get('PORT', 5000)
        
        print(f"Starting Autolycus API on {host}:{port}")
        logger.info(f"Starting Autolycus API on {host}:{port}")
        
        # List all registered routes for debugging
        print("\nRegistered routes:")
        for rule in app.url_map.iter_rules():
            print(f"  {rule.rule} -> {rule.endpoint} ({','.join(rule.methods - {'HEAD', 'OPTIONS'})})")
        print()
        
        serve(app, host=host, port=port)
    except Exception as e:
        print(f"ERROR: {e}", flush=True)
        logger.error(f"Error starting API: {e}", exc_info=True)
        raise


if __name__ == '__main__':
    logging.basicConfig(
        level=logging.INFO,
        format='%(levelname)s %(asctime)s.%(msecs)d %(name)s: %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )
    run_api()
