"""
Autolycus REST API Application

This module creates and configures the Flask application for the
Autolycus REST API, providing endpoints for raids, builds, and damage
calculator features.

Security:
    All protected endpoints require token-based authentication via
    ephemeral links generated by the Discord bot. See api/security.py
    for implementation details.

Usage:
    from api.app import create_app
    app = create_app()
    app.run()
"""
import gzip
import logging
import os
from typing import Optional

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_cors import CORS
from werkzeug.middleware.proxy_fix import ProxyFix
from core.logging_config import setup_logging

# Load environment variables FIRST
load_dotenv()

from core.config import get_config
from api.routes.auth import auth_bp
from api.routes.builds import builds_bp
from api.routes.damage import damage_bp
from api.routes.nuke_targets import nuke_targets_bp
from api.routes.raids import raids_bp
from api.routes.stats import stats_bp

logger = logging.getLogger(__name__)


def create_app(config_object: Optional[object] = None) -> Flask:
    """
    Application factory for creating Flask app instances.
    
    Args:
        config_object: Optional configuration object. If not provided,
                      configuration is loaded based on FLASK_ENV.
    
    Returns:
        Configured Flask application instance.
    """
    app = Flask(__name__)
    
    # Load configuration
    if config_object:
        app.config.from_object(config_object)
    else:
        config = get_config()
        app.config.from_object(config)

    
    # Ensure required config values are set
    if not app.config.get('SECRET_KEY'):
        app.config['SECRET_KEY'] = os.urandom(32).hex()
        logger.warning("No SECRET_KEY configured, using random key. "
                      "Tokens will be invalidated on restart.")

    # Configure CORS
    cors_origins = app.config.get('CORS_ORIGINS', ['*'])
    supports_credentials = '*' not in cors_origins
    CORS(app, origins=cors_origins, supports_credentials=supports_credentials,
         allow_headers=['Content-Type', 'Authorization'],
         methods=['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE'])

    # Proxy handling (for correct client IPs behind reverse proxy)
    if app.config.get("TRUST_PROXY_HEADERS"):
        app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1)

    # Register blueprints
    app.register_blueprint(auth_bp)
    app.register_blueprint(raids_bp)
    app.register_blueprint(nuke_targets_bp)
    app.register_blueprint(builds_bp)
    app.register_blueprint(damage_bp)
    app.register_blueprint(stats_bp)

    # Security headers + gzip for large JSON payloads (raids/nuke lists).
    @app.after_request
    def add_security_headers(response):
        if app.config.get("SECURITY_HEADERS_ENABLED", True):
            response.headers.setdefault("X-Content-Type-Options", "nosniff")
            response.headers.setdefault("X-Frame-Options", "DENY")
            response.headers.setdefault("Referrer-Policy", "no-referrer")
            response.headers.setdefault(
                "Content-Security-Policy",
                "default-src 'none'; frame-ancestors 'none'; base-uri 'none'"
            )
            # Enable HSTS if request is over HTTPS
            if request.is_secure:
                response.headers.setdefault(
                    "Strict-Transport-Security",
                    "max-age=31536000; includeSubDomains"
                )
        if request.path.startswith("/api/"):
            response.headers.setdefault("Cache-Control", "no-store")
            response.headers.setdefault("Pragma", "no-cache")

        # Compress large JSON when the client accepts gzip (cuts ~7MB raids payloads
        # down substantially over the wire).
        accept = request.headers.get("Accept-Encoding", "")
        if (
            response.status_code == 200
            and response.direct_passthrough is False
            and "gzip" in accept
            and "Content-Encoding" not in response.headers
            and response.mimetype
            and "json" in response.mimetype
        ):
            data = response.get_data()
            if len(data) >= 2048:
                compressed = gzip.compress(data, compresslevel=5)
                if len(compressed) < len(data):
                    response.set_data(compressed)
                    response.headers["Content-Encoding"] = "gzip"
                    response.headers["Content-Length"] = str(len(compressed))
                    response.headers["Vary"] = "Accept-Encoding"

        return response
    
    # Health check endpoints for API clients and infrastructure probes.
    @app.route('/api/health')
    @app.route('/health')
    @app.route('/healthz')
    def health_check():
        """Health check endpoint for monitoring."""
        return jsonify({
            'status': 'healthy',
            'service': 'autolycus-api',
            'version': os.getenv('version', 'unknown'),
        }), 200
    
    # Root endpoint
    @app.route('/')
    def root():
        """Root endpoint."""
        return jsonify({
            'message': 'Autolycus API',
            'documentation': '/api/docs',
            'health': '/api/health',
        }), 200
    
    # Error handlers
    @app.errorhandler(404)
    def not_found(error):
        """Handle 404 errors."""
        return jsonify({
            'error': 'Not found',
            'message': 'The requested resource does not exist.',
            'code': 'NOT_FOUND'
        }), 404
    
    @app.errorhandler(500)
    def internal_error(error):
        """Handle 500 errors."""
        logger.error(f"Internal server error: {error}", exc_info=True)
        return jsonify({
            'error': 'Internal server error',
            'message': 'An unexpected error occurred.',
            'code': 'INTERNAL_ERROR'
        }), 500
    
    @app.errorhandler(405)
    def method_not_allowed(error):
        """Handle 405 errors."""
        return jsonify({
            'error': 'Method not allowed',
            'message': 'This HTTP method is not supported for this endpoint.',
            'code': 'METHOD_NOT_ALLOWED'
        }), 405

    @app.errorhandler(413)
    def request_entity_too_large(error):
        """Handle oversized request bodies."""
        return jsonify({
            'error': 'Payload too large',
            'message': 'Request body exceeds the maximum allowed size.',
            'code': 'PAYLOAD_TOO_LARGE'
        }), 413

    @app.errorhandler(429)
    def rate_limit_exceeded(error):
        """Handle rate limit violations."""
        return jsonify({
            'error': 'Too many requests',
            'message': 'Rate limit exceeded. Please slow down your requests.',
            'code': 'RATE_LIMITED'
        }), 429
    
    logger.info(f"Autolycus API initialized with CORS origins: {cors_origins}")
    
    return app


def run_api():
    """
    Run the API server using Waitress (production WSGI server).
    
    This function is called when running the API standalone.
    """
    setup_logging(process_name="api", level=os.getenv("LOG_LEVEL", "INFO"))
    
    try:
        from waitress import serve
        
        app = create_app()
        host = app.config.get('HOST', '0.0.0.0')
        port = app.config.get('PORT', 5000)
        
        print(f"Starting Autolycus API on {host}:{port}")
        logger.info(f"Starting Autolycus API on {host}:{port}")
        
        # List all registered routes for debugging
        print("\nRegistered routes:")
        for rule in app.url_map.iter_rules():
            print(f"  {rule.rule} -> {rule.endpoint} ({','.join(rule.methods - {'HEAD', 'OPTIONS'})})")
        print()
        
        # Waitress settings (DoS resilience)
        serve(
            app,
            host=host,
            port=port,
            threads=app.config.get('WAITRESS_THREADS', 8),
            connection_limit=app.config.get('WAITRESS_CONNECTION_LIMIT', 200),
            channel_timeout=app.config.get('WAITRESS_CHANNEL_TIMEOUT', 30),
        )
    except Exception as e:
        print(f"ERROR: {e}", flush=True)
        logger.error(f"Error starting API: {e}", exc_info=True)
        raise


if __name__ == '__main__':
    setup_logging(process_name="api", level=os.getenv("LOG_LEVEL", "INFO"))
    run_api()
