"""
Security Module

This module provides token-based authentication for the API using
itsdangerous.URLSafeTimedSerializer. Tokens are generated by the Discord bot
and validated by the API to ensure stateless authentication via ephemeral links.

Security Model:
- Tokens encode the user_id and timestamp, signed with SECRET_KEY
- Tokens expire after TOKEN_MAX_AGE seconds
- Any modification to the token invalidates the signature
- This prevents adversaries from accessing another user's data
"""
import logging
from functools import wraps
from typing import Any, Callable, Optional, TypeVar, cast

from flask import current_app, jsonify, request, session
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer

logger = logging.getLogger(__name__)

# Type for decorated functions
F = TypeVar('F', bound=Callable[..., Any])


class TokenError(Exception):
    """Base exception for token-related errors."""
    pass


class TokenExpiredError(TokenError):
    """Raised when a token has expired."""
    pass


class TokenInvalidError(TokenError):
    """Raised when a token is invalid or tampered with."""
    pass


def get_serializer() -> URLSafeTimedSerializer:
    """
    Create a URLSafeTimedSerializer instance using the app's secret key.
    
    Returns:
        URLSafeTimedSerializer: Configured serializer for token operations.
    """
    return URLSafeTimedSerializer(
        current_app.config['SECRET_KEY'],
        salt=current_app.config.get('TOKEN_SALT', 'autolycus-ephemeral-link')
    )


def generate_token(user_id: int, timestamp: int, **extra_data: Any) -> str:
    """
    Generate a signed token for a user session.
    
    This function creates an ephemeral link token that encodes the user's
    identity and the timestamp of the data request. The token is signed
    with the app's SECRET_KEY, making it impossible to forge.
    
    Args:
        user_id: The Discord user ID.
        timestamp: The Unix timestamp of the data generation.
        **extra_data: Additional data to encode in the token.
    
    Returns:
        str: A URL-safe signed token string.
    
    Example:
        >>> token = generate_token(123456789, 1704067200, data_type="raids")
        >>> # Token can be appended to URLs: ?token=<token>
    """
    serializer = get_serializer()
    payload = {
        'user_id': user_id,
        'timestamp': timestamp,
        **extra_data
    }
    return serializer.dumps(payload)


def verify_token(token: str, max_age: Optional[int] = None) -> dict[str, Any]:
    """
    Verify and decode a signed token.
    
    Args:
        token: The signed token string to verify.
        max_age: Maximum age of the token in seconds. If None, uses app config.
    
    Returns:
        dict: The decoded payload containing user_id, timestamp, and any extra data.
    
    Raises:
        TokenExpiredError: If the token has exceeded its maximum age.
        TokenInvalidError: If the token signature is invalid or tampered with.
    """
    serializer = get_serializer()
    
    if max_age is None:
        max_age = current_app.config.get('TOKEN_MAX_AGE', 3600 * 24 * 7)
    
    try:
        payload = serializer.loads(token, max_age=max_age)
        return cast(dict[str, Any], payload)
    except SignatureExpired as e:
        logger.warning(f"Token expired: {e}")
        raise TokenExpiredError("Token has expired. Please request a new link.") from e
    except BadSignature as e:
        logger.warning(f"Invalid token signature: {e}")
        raise TokenInvalidError("Invalid token. Access denied.") from e


def require_token(f: F) -> F:
    """
    Decorator to require a valid token for API endpoints.
    
    The token can be provided in:
    1. Query parameter: ?token=<token>
    2. Authorization header: Authorization: Bearer <token>
    
    On success, the decoded token payload is added to the request context
    as `request.token_payload`, containing:
    - user_id: The authenticated user's Discord ID
    - timestamp: The data generation timestamp
    - Any additional data encoded in the token
    
    On failure, returns a 401 Unauthorized response with error details.
    
    Example:
        @app.route('/api/raids')
        @require_token
        def get_raids():
            user_id = request.token_payload['user_id']
            timestamp = request.token_payload['timestamp']
            # ... fetch and return data
    """
    @wraps(f)
    def decorated(*args: Any, **kwargs: Any) -> Any:
        # Try to get token from query parameter first
        token = request.args.get('token')
        
        # Fall back to Authorization header
        if not token:
            auth_header = request.headers.get('Authorization', '')
            if auth_header.startswith('Bearer '):
                token = auth_header[7:]
        
        if not token:
            logger.warning("Request missing token")
            return jsonify({
                'error': 'Authentication required',
                'message': 'A valid token is required to access this resource.',
                'code': 'TOKEN_MISSING'
            }), 401
        
        try:
            payload = verify_token(token)
            # Attach payload to request for use in the endpoint
            request.token_payload = payload  # type: ignore
            return f(*args, **kwargs)
        except TokenExpiredError as e:
            return jsonify({
                'error': 'Token expired',
                'message': str(e),
                'code': 'TOKEN_EXPIRED'
            }), 401
        except TokenInvalidError as e:
            return jsonify({
                'error': 'Invalid token',
                'message': str(e),
                'code': 'TOKEN_INVALID'
            }), 401
    
    return cast(F, decorated)


def optional_token(f: F) -> F:
    """
    Decorator for endpoints where token authentication is optional.
    
    If a valid token is provided, `request.token_payload` will contain
    the decoded data. If no token or an invalid token is provided,
    `request.token_payload` will be None.
    
    Useful for endpoints that can work both authenticated and unauthenticated.
    """
    @wraps(f)
    def decorated(*args: Any, **kwargs: Any) -> Any:
        token = request.args.get('token')
        
        if not token:
            auth_header = request.headers.get('Authorization', '')
            if auth_header.startswith('Bearer '):
                token = auth_header[7:]
        
        request.token_payload = None  # type: ignore
        
        if token:
            try:
                request.token_payload = verify_token(token)  # type: ignore
            except (TokenExpiredError, TokenInvalidError):
                pass  # Token invalid, but endpoint doesn't require it
        
        return f(*args, **kwargs)
    
    return cast(F, decorated)


def _get_session_user_id() -> Optional[int]:
    """Return authenticated Discord user ID from server session."""
    raw = session.get("discord_user_id")
    try:
        return int(raw) if raw is not None else None
    except (TypeError, ValueError):
        return None


def require_discord_session(f: F) -> F:
    """Decorator requiring an authenticated Discord OAuth session."""

    @wraps(f)
    def decorated(*args: Any, **kwargs: Any) -> Any:
        user_id = _get_session_user_id()
        if user_id is None:
            return jsonify({
                'error': 'Authentication required',
                'message': 'Please sign in with Discord to access this resource.',
                'code': 'AUTH_REQUIRED'
            }), 401
        request.session_user_id = user_id  # type: ignore[attr-defined]
        return f(*args, **kwargs)

    return cast(F, decorated)


def optional_discord_session(f: F) -> F:
    """Decorator that attaches session user ID if present."""

    @wraps(f)
    def decorated(*args: Any, **kwargs: Any) -> Any:
        request.session_user_id = _get_session_user_id()  # type: ignore[attr-defined]
        return f(*args, **kwargs)

    return cast(F, decorated)
